// [Claude] KIERUNEK 1.2: kontekst laczacy App.tsx (stan + akcje) z komponentami zakladek.
// App buduje obiekt GameApi przy kazdym renderze i podaje go providerem; zakladki czytaja
// go hookiem useGameApi(). Interfejs jest jawny (a nie wnioskowany), zeby tsc pilnowal
// zgodnosci obu stron.
import { createContext, useContext } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import type { GameState } from '../hooks/useGameState';


export interface GameApi {
  activeQueue: string | null;
  activeQueue2: string | null;
  activeSmuggle: string | null;
  addCompanyCapital: (companyId: string, amount: number) => void;
  addToast: (title: string, desc: string) => void;
  autoStartRun: (routeId: string) => void;
  bidInAuction: () => void;
  blackmailHelperTW: (helperId: string) => void;
  bribe: () => void;
  bribeBazarCustoms: () => void;
  bribeEuAuditor: () => void;
  bribeKrrit: () => void;
  bribeSBHandler: (helperId: string) => void;
  bribeSbChief: () => void;
  broadcastPoliticalSpot: (stationId: string, alignment: 'government' | 'solidarity') => void;
  buyAsset: (assetType: 'srebro' | 'krugerrand' | 'sztabkaZlota', payWith: 'pln' | 'dollars') => void;
  buyBaltonaUpgrade: (upgradeId: string) => void;
  buySeaUpgrade: (upgradeId: string) => void;
  buyBazarItem: (itemId: string, amount: number) => void;
  buyBlackMarketOffer: (offerId: string) => void;
  buyBlackMarketWeapon: (weaponId: string, qty?: number) => void;
  buyBondPRL: () => void;
  buyBondSolidarnos: (payWith: 'pln' | 'dollars') => void;
  buyBonyPewex: (amount: number) => void;
  buyBusiness: (id: string, costDollars: number) => void;
  buyCOCOMItem: (itemId: string) => void;
  buyCocomVehicle: (vehicleId: string) => void;
  buyCounterIntel: () => void;
  buyCrisisRealEstate: (projectId: string) => void;
  buyCurrencyOption: (presetId: string) => void;
  buyEuroBond: (bondId: string) => void;
  buyDollarPremium: () => void;
  buyDotcomUpgrade: (upgradeId: string) => void;
  buyElectionUpgrade: (upgradeId: string) => void;
  buyGangUnit: (unitId: string, qty?: number) => void;
  buyGpwInsiderTip: (currency: 'pln' | 'dollars') => void;
  buyHelper: (id: string, cost: number) => void;
  buyInflationUpgrade: (id: string, currency: 'pln' | 'dollars', cost: number) => void;
  buyInk: () => void;
  buyInstantCzarnyRynek: (itemId: string) => void;
  buyMediaAntenna: (antennaId: string) => void;
  buyMediaStation: (stationId: string) => void;
  buyNfiCompany: (compId: string) => void;
  buyPaper: () => void;
  buyPrintingSupplies: (type: 'paper' | 'ink', payWith: 'pln' | 'usd') => void;
  buyProgramLicense: (programId: string) => void;
  buyMordorFloor: () => void;
  buyMordorUpgrade: (upgradeId: string) => void;
  buyRealEstate: (projectId: string, useChf: boolean) => void;
  buyShares: (stockId: string, amount: number) => void;
  buySyndicateUpgrade: (upgradeId: string) => void;
  buyTeczkaIPN: () => void;
  buyVatUpgrade: (upgradeId: string) => void;
  buyWholesale: (itemId: string, payWith: 'pln' | 'dollars') => void;
  claimMediaSponsorshipContract: (stationId: string) => void;
  claimVatRefund: () => void;
  concludeNegotiations: () => void;
  createOffshoreDeposit: (amount: number, currency: 'pln' | 'dollars', depositTypeId: string) => void;
  currentRankIndex: number; // TODO-typ (wartosc pochodna z App)
  deliverForRuble: (itemId: string, amountRequired: number, rubleReward: number) => void;
  deliverForTalony: (itemId: string, amountRequired: number, talonyReward: number) => void;
  denominatePln: () => void;
  dismissHelperTW: (helperId: string) => void;
  dispatchBazarTransport: (routeId: string) => void;
  distributePisma: (amount: number) => void;
  exchangeGoodsForBaltona: (itemId: string, amount: number, rewardBony: number) => void;
  exchangeRubleForDollars: () => void;
  exchangeTalonyForKartki: () => void;
  finishCrisisRealEstate: (projectId: string) => void;
  fireNfiEmployees: (compId: string, amount: number) => void;
  formatSpeedrunTime: (sec: number) => string;
  fundSolidarnoscDollars: (amount: number, dollarCost: number) => void;
  fundSolidarnoscKartki: (amount: number, kartkiCost: number) => void;
  fundSolidarnoscPln: (amount: number, plnCost: number) => void;
  fundSolidarnoscRuble: (amount: number, rubleCost: number) => void;
  fundSolidarnoscTalony: (amount: number, talonyCost: number) => void;
  helperMult: number; // TODO-typ (wartosc pochodna z App)
  hireBankAdvisor: () => void;
  hireCocomPersonnel: (personnelId: string) => void;
  hireMafiaProtection: (protId: string) => void;
  hireNfiEmployees: (compId: string, amount: number) => void;
  hireRedDirector: (companyId: string) => void;
  interactDebate: (optionId: string) => void;
  isKartkiRequired: (item: { kartkiCost?: number }) => boolean;
  issueJdgContract: () => void;
  lata2000SubTab: 'ue' | 'dotcom' | 'deweloperka' | 'zmywak' | 'polityka' | 'raje';
  lata90SubTab: 'bazar' | 'nfi' | 'media' | 'mafia';
  launchRally: (regionId: string, leaderId: string) => void;
  launderCocomProceeds: (amount: number, target?: 'pln' | 'usd') => void;
  modernizeNfiInfrastructure: (compId: string) => void;
  negotiateNfiUnions: (compId: string) => void;
  newCompanyGoods: 'electronics' | 'steel' | 'fuel';
  newCompanyName: string;
  offshoreDepositAmount: string;
  offshoreExchangeAmount: string;
  offshoreTransferAmount: string;
  offshoreWashAmount: string;
  openRegionalCommittee: (regionId: string) => void;
  openSwissAccount: (payWith: 'pln' | 'dollars') => void;
  organizeMordorPizza: () => void;
  pacifyNfiStrike: (compId: string) => void;
  payOffshoreCredit: () => void;
  pracuj: () => void;
  printCampaignMaterial: (materialId: string) => void;
  przemytSubTab: 'land' | 'sea' | 'nomenklatura';
  queueProgress: number;
  queueProgress2: number;
  realTime: Date;
  recruitTwInNomenklatura: (companyId: string) => void;
  recruitMordorEmployee: () => void;
  redeemSolidarnosBonds: () => void;
  registerLiechtensteinTrust: () => void;
  registerNomenklaturaCompany: (companyId: string) => void;
  registerShellCompany: (name: string, goodsType: 'electronics' | 'steel' | 'fuel') => void;
  resetGame: (prestigeToEarn: number, destination: 'nrf' | 'austria' | 'usa' | 'kanada' | 'australia' | null, startSpeedrun?: boolean) => void;
  resolveVatAudit: (companyId: string, method: 'bribe' | 'lawyer') => void;
  restructureChfDebt: () => void;
  runElectionsFirstRound: () => void;
  runElectionsSecondRound: () => void;
  runInvestigation: () => void;
  runTabloidInvestigation: (stationId: string) => void;
  selectedStockId: string;
  sellAsset: (assetType: 'srebro' | 'krugerrand' | 'sztabkaZlota', receiveIn: 'pln' | 'dollars') => void;
  sellBazarItem: (itemId: string, amount: number) => void;
  sellBonyPewex: (amount: number) => void;
  sellCrisisRealEstate: (projectId: string) => void;
  sellEurosToPln: () => void;
  sellItem: (id: string, price: number, amount?: number) => void;
  sellItemDollars: (id: string, price: number, amount?: number) => void;
  sellRealEstate: (projectId: string) => void;
  sellShares: (stockId: string, amount: number) => void;
  sendCocomShipment: (itemId: string, contactId: string, route: 'lad_road' | 'sea_route' | 'air_cargo') => void;
  sendOffshoreCourier: (amount: number, currency: 'pln' | 'dollars') => void;
  sendWorkerToZmywak: (count: number) => void;
  setLata2000SubTab: Dispatch<SetStateAction<'ue' | 'dotcom' | 'deweloperka' | 'zmywak' | 'polityka' | 'raje'>>;
  setLata90SubTab: Dispatch<SetStateAction<'bazar' | 'nfi' | 'media' | 'mafia'>>;
  setMediaSlot: (stationId: string, slotId: string, programId: string | null) => void;
  setNewCompanyGoods: Dispatch<SetStateAction<'electronics' | 'steel' | 'fuel'>>;
  setNewCompanyName: Dispatch<SetStateAction<string>>;
  setOffshoreDepositAmount: Dispatch<SetStateAction<string>>;
  setOffshoreExchangeAmount: Dispatch<SetStateAction<string>>;
  setOffshoreTransferAmount: Dispatch<SetStateAction<string>>;
  setOffshoreWashAmount: Dispatch<SetStateAction<string>>;
  setPrzemytSubTab: Dispatch<SetStateAction<'land' | 'sea' | 'nomenklatura'>>;
  setSelectedStockId: Dispatch<SetStateAction<string>>;
  setSpeedrunChecked: Dispatch<SetStateAction<boolean>>;
  setVatOffshoreAmountInput: Dispatch<SetStateAction<string>>;
  showAlert: (message: string, title?: string, type?: 'info' | 'error' | 'success' | 'raid' | 'pap') => void;
  showConfirm: (message: string, onConfirm: () => void, title?: string) => void;
  smuggleProgress: number;
  speedrunChecked: boolean;
  startEuProject: (projectId: string) => void;
  startOkraglyStol: () => void;
  startPrinting: () => void;
  startQueue: (id: string, cost: number, kartkiCost?: number) => void;
  stopQueue: (slot: 1 | 2) => void;
  startSeaSmuggle: (routeId: string) => void;
  startSmuggle: (id: string, cost: number) => void;
  state: GameState;
  takeChfMortgage: (amountChf: number) => void;
  takeOffshoreCredit: () => void;
  toggleCompanyActive: (companyId: string) => void;
  toggleLobbyBill: (id: string) => void;
  toggleVatCarousel: () => void;
  transferToCampaign: (amount: number, currency: 'pln' | 'usd') => void;
  transferToOffshore: (amount: number) => void;
  unlockElections: () => void;
  unlockExportContact: (contactId: string) => void;
  unlockFazaM: () => void;
  unlockFazaN: () => void;
  unlockFazaS: () => void;
  unlockFazaW: () => void;
  unlockSyndicate: () => void;
  updateState: (updates: Partial<GameState> | ((s: GameState) => GameState)) => void;
  upgradeBazarWarehouse: (upgradeId: string) => void;
  upgradeHelper: (helperId: string) => void;
  upgradeLeasing: (companyId: string) => void;
  upgradeTaxLevel: () => void;
  vatOffshoreAmountInput: string;
  washOffshoreMoney: (amount: number) => void;
  wholesalePrices: Record<string, { pln: number, usd: number }>;
  wireTransferToSwiss: (amount: number, currency: 'pln' | 'dollars') => void;
  withdrawFromOffshore: (amount: number) => void;
  zurichExchange: (amount: number, from: 'pln' | 'usd') => void;
}

export const GameApiContext = createContext<GameApi | null>(null);

export const useGameApi = (): GameApi => {
  const api = useContext(GameApiContext);
  if (!api) throw new Error('useGameApi: brak GameApiContext.Provider nad komponentem');
  return api;
};
